# Numpy Review
## 1D Array

In [1]:
import numpy as np

In [20]:
t = np.array([0, 1, 2, 3, 4, 5, 6])
print(t)

[0 1 2 3 4 5 6]


In [24]:
print('차원 Rank of t: ', t.ndim)
print('Shape of t: ', t.shape)
t.dtype

차원 Rank of t:  1
Shape of t:  (7,)


dtype('int32')

### Element 확인

In [13]:
print('t[0] t[1] t[-1] = ',t[0], t[1], t[-1])

t[0] t[1] t[-1] =  0.0 1.0 6.0


### Slicing 확인

In [14]:
print('t[2:5] t[4:-1] = ',t[2:5], t[4:-1])

t[2:5] t[4:-1] =  [2. 3. 4.] [4. 5.]


In [15]:
print('t[:2] t[3:] =',t[:2], t[3:])

t[:2] t[3:] = [0. 1.] [3. 4. 5. 6.]


## 2D Array

In [16]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [18]:
print('차원 Rank of t: ', t.ndim)
print('Shape of t: ', t.shape)

차원 Rank of t:  2
Shape of t:  (4, 3)
