# PyTorch Tensor
## 1D Array with Torch

In [44]:
import torch

t1 = torch.Tensor([0, 1, 2, 3, 4, 5, 6])
t2 = torch.Tensor([0., 1., 2., 3., 4., 5., 6.])
print(t1)
print(t2)

tensor([0., 1., 2., 3., 4., 5., 6.])
tensor([0., 1., 2., 3., 4., 5., 6.])


In [45]:
print('t1  차원 dim: ',t1.dim())
print('t1     shape: ',t1.shape)
print('t1      size: ',t1.size())
print('t1 data type: ',t1.type())

print('t2  차원 dim: ',t2.dim())
print('t2     shape: ',t2.shape)
print('t2      size: ',t2.size())
print('t2 data type: ',t2.type())

t1  차원 dim:  1
t1     shape:  torch.Size([7])
t1      size:  torch.Size([7])
t1 data type:  torch.FloatTensor
t2  차원 dim:  1
t2     shape:  torch.Size([7])
t2      size:  torch.Size([7])
t2 data type:  torch.FloatTensor


In [46]:
t3 = torch.tensor([0, 1, 2, 3, 4, 5, 6])
t4 = torch.tensor([0., 1., 2., 3., 4., 5., 6.])
print(t3)
print(t4)

tensor([0, 1, 2, 3, 4, 5, 6])
tensor([0., 1., 2., 3., 4., 5., 6.])


In [52]:
print('t3  차원 dim: ',t3.dim())
print('t3     shape: ',t3.shape)
print('t3     shape: ',t3.size())
print('t3 data type: ',t3.type())

print('t4  차원 dim: ',t4.dim())
print('t4     shape: ',t4.shape)
print('t4     shape: ',t4.size())
print('t4 data type: ',t4.type())

t3  차원 dim:  1
t3     shape:  torch.Size([7])
t3     shape:  torch.Size([7])
t3 data type:  torch.LongTensor
t4  차원 dim:  1
t4     shape:  torch.Size([7])
t4     shape:  torch.Size([7])
t4 data type:  torch.FloatTensor


## _**np.array의 default data type은 Int**_
## _**torch.tensor의 default data type은 LONG**_
## _**torch.Tensor의 default data type은 Float**_

### Element

In [21]:
print(t[0], t[1], t[-1])

tensor(0.) tensor(1.) tensor(6.)


### Slicing

In [22]:
print(t[2:5], t[4:-1])    
print(t[:2], t[3:])

tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


## 2D Array with Torch

In [48]:
tt = torch.tensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])
print(tt)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [51]:
print('tt  차원 dim: ',tt.dim())
print('tt     shape: ',tt.shape)
print('tt      size: ',tt.size())

tt  차원 dim:  2
tt     shape:  torch.Size([4, 3])
tt      size:  torch.Size([4, 3])


In [56]:
print(tt[:,1])
print(tt[:,1].size())
print(tt[:,:-1])

tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


## 4D

In [57]:
ttt = torch.FloatTensor([[[[1, 2, 3, 4],
                         [5, 6, 7, 8],
                         [9, 10, 11, 12]],
                       [[13, 14, 15, 16],
                        [17, 18, 19, 20],
                        [21, 22, 23, 24]]
                       ]])

In [58]:
print(ttt.dim())  # rank  = 4
print(ttt.size()) # shape = (1, 2, 3, 4)

4
torch.Size([1, 2, 3, 4])
